baseURL:  "https://www.flyinggrizzly.io/childhood-in-the-sunlight/"
languageCode: "en-us"

title: "Childhood in the Sunlight"

theme: 'hyde'

params:
  description: 'a [*Forged in the Dark*](https://bladesinthedark.com/licensing) game about kids going on adventures with friends, and the bittersweet joy of growing up'
  themeColor: 'theme-base-0a'
